################################################################################
# Copyright (c) 2021,2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

# BPDM application specific configuration
bpdm:
  # Name of this application (shown in Swagger) (on default set by maven resource filtering)
  name: '@project.name@'
  # Version of this application (shown in Swagger) (on default set by maven resource filtering)
  version: '@project.version@'
  # Description of this application (shown in Swagger) (on default set by maven resource filtering)
  description: '@project.description@'
  bridge:
    # Page size for querying Gate
    query-page-size: 100
  client:
    gate:
      # The base-url of the Gate-API
      base-url: http://localhost:8081/
      # Whether authentication should be used to connect to the Gate
      security-enabled: false
    # The base-url of the Pool-API
    pool:
      # The base-url of the Pool-API
      base-url: http://localhost:8080/
      # Whether authentication should be used to connect to the Pool
      security-enabled: false
  logging:
    # Default username logged if no user could be authenticated in the request
    unknown-user: Anonymous
  datasource:
    # Host name of the used datasource
    host: localhost
    # The database schema to use for this application
    schema: bpdm-bridge-dummy
#
# From here on are framework and dependency configuration
# More information about those properties can be taken from the respective documentation of Spring or the dependency
#
server:
  # Change default port to avoid clash with other BPDM applications
  port: 8083
logging:
  pattern:
    # Use BPDM custom log pattern
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %green([%-10.10X{user:-System}]) %magenta([%-10.10X{request:-No Request}]) %yellow([%-15.15t]) %cyan(%-40.40logger{39}) : %m%n%wEx"
  level:
    # On default show only logs from INFO and above
    root: INFO
    com:
      catenax:
        bpdm:
          bridge:
            # Logs from this application's package should be DEBUG and above
            dummy: DEBUG
management:
  endpoint:
    health:
      probes:
        # Enable actuator health endpoints for probing
        enabled: true
  health:
    livenessState:
      # Include liveness state in health response (responsive at all)
      enabled: true
    readinessState:
      # Include readiness state in health response (ready to accept traffic)
      enabled: true
spring:
  datasource:
    # We use postgres as datasource
    driverClassName: org.postgresql.Driver
    # No password on default (Change for production)
    password: ''
    # Connect to postgres database over jdbc protocol
    url: jdbc:postgresql://${bpdm.datasource.host}:5432/bpdm
    # Default username for BPDM applications
    username: bpdm
  flyway:
    # Activate flyway for automatic database migration
    enabled: true
    # Apply migrations to this application's default schema
    schemas: ${bpdm.datasource.schema}
  jpa:
    # JPA should speak Postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      # We use hibernate as JPA implementation
      hibernate:
        # Hibernate should assume the default schema of this application on default
        default_schema: ${bpdm.datasource.schema}
        # Send updates and inserts out in batches to decrease network connections to the database
        jdbc:
          batch_size: 16
        order_inserts: true
        order_updates: true
springdoc:
  api-docs:
    # Generate Open-API document
    enabled: true
    # Set custom path for the document
    path: /docs/api-docs
  swagger-ui:
    # Swagger UI should not be available at its default URL (instead on location defined in path)
    disable-swagger-default-url: true
    # Override default Swagger UI location
    path: /ui/swagger-ui
    # Show validation specific information for properties (pattern, minimum, maximum, etc...)
    show-common-extensions: true
